services:
  - type: web
    name: jobcompass-api
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./docker/api/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: BACKEND_CORS_ORIGINS
        value: https://kirillqaengineer.github.io
      - key: BACKEND_ALLOWED_HOSTS
        value: jobcompass-api.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: JOOBLE_API_KEY
        sync: false
