"""create applications table

Revision ID: 3a8287b7287e
Revises: e0ce7df7fcab
Create Date: 2026-07-12 19:44:52.185066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8287b7287e'
down_revision: Union[str, Sequence[str], None] = 'e0ce7df7fcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('job_company', sa.String(), nullable=False),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('job_location', sa.String(), nullable=True),
    sa.Column('job_work_format', sa.String(), nullable=True),
    sa.Column('job_published_at', sa.String(), nullable=True),
    sa.Column('job_source', sa.String(), nullable=False),
    sa.Column('job_external_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='applied', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_source', 'job_external_id', name='uq_applications_user_job_identity')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_company'), 'applications', ['job_company'], unique=False)
    op.create_index(op.f('ix_applications_job_external_id'), 'applications', ['job_external_id'], unique=False)
    op.create_index(op.f('ix_applications_job_source'), 'applications', ['job_source'], unique=False)
    op.create_index(op.f('ix_applications_job_title'), 'applications', ['job_title'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_title'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_source'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_external_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_company'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
