"""create resume_profiles table

Revision ID: bc88c21f53d4
Revises: b6fa46cf6c7b
Create Date: 2026-07-01 00:55:46.766534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc88c21f53d4'
down_revision: Union[str, Sequence[str], None] = 'b6fa46cf6c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('technologies', sa.Text(), nullable=False),
    sa.Column('english_level', sa.String(length=100), nullable=False),
    sa.Column('preferred_roles', sa.Text(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_profiles')
    # ### end Alembic commands ###
