"""add stable job identity

Revision ID: d55e45c32951
Revises: 65ab262147e7
Create Date: 2026-07-08 12:01:26.420975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55e45c32951'
down_revision: Union[str, Sequence[str], None] = '65ab262147e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_interactions', sa.Column('job_source', sa.String(), nullable=True))
    op.add_column('job_interactions', sa.Column('job_external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_job_interactions_job_external_id'), 'job_interactions', ['job_external_id'], unique=False)
    op.create_index(op.f('ix_job_interactions_job_source'), 'job_interactions', ['job_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_interactions_job_source'), table_name='job_interactions')
    op.drop_index(op.f('ix_job_interactions_job_external_id'), table_name='job_interactions')
    op.drop_column('job_interactions', 'job_external_id')
    op.drop_column('job_interactions', 'job_source')
    # ### end Alembic commands ###
